[project]
name = "codesnap.nvim"
version = "0.1.0"
description = "📸 Snapshot plugin that can make pretty code snapshots with real-time previews for Neovim"
author = "Mist"
email = "0xjwlabs@gmail.com"
